<?php
/* --------------------------------------------------------------
   novalnet_payment.lang.inc.php
   --------------------------------------------------------------
*/

$t_language_text_section_content_array = [
    'MODULE_PAYMENT_NOVALNET_REFUND_TITLE'                            => 'Erstattungsverfahren',
    'MODULE_PAYMENT_NOVALNET_TRANSACTION_ID'                          => 'Novalnet-Transaktions-ID: ',
    'MODULE_PAYMENT_NOVALNET_PAYMENT_REFUND_CONFIRM'                  => 'Sind Sie sicher, dass Sie den Betrag erstatten wollen?',
    'MODULE_PAYMENT_NOVALNET_REFUND_AMT_TITLE'                        => 'Bitte geben Sie den Erstattungsbetrag ein',
    'MODULE_PAYMENT_NOVALNET_AMOUNT_EX'                               => '   (in der kleinsten Währungseinheit, z.B. 100 Cent = entsprechen 1.00 EUR)',
    'MODULE_PAYMENT_NOVALNET_REFUND_REASON_TITLE'                     => 'Grund der Rückerstattung/Stornierung',
    'MODULE_PAYMENT_NOVALNET_CONFIRM_TEXT'                            => 'Bestätigen',
    'MODULE_PAYMENT_NOVALNET_BACK_TEXT'                               => 'Zurück',
    'MODULE_PAYMENT_NOVALNET_AMOUNT_ERROR_MESSAGE'                    => 'Ungültiger Betrag',
    'ERROR_ORDER_ACTION_NOT_FOUND'                                    => 'Der angeforderte Aktionsprozess wurde nicht gefunden',
    'MODULE_PAYMENT_NOVALNET_REFUND_PARENT_TID_MSG'                   => 'Die Rückerstattung für die TID: %1$s mit dem Betrag %2$s wurde veranlasst.',
    'MODULE_PAYMENT_NOVALNET_REFUND_CHILD_TID_MSG'                    => ' Die neue TID: %s für den erstatteten Betrag',
    'MODULE_PAYMENT_NOVALNET_INSTALMENT_SUMMARY_BACKEND'              => 'Zusammenfassung der Ratenzahlung',
    'MODULE_PAYMENT_NOVALNET_INSTALMENT_CANCEL_ADMIN_TEXT'            => 'Ratenzahlung Stornieren',
    'MODULE_PAYMENT_NOVALNET_ALLCYCLES_ERROR_MESSAGE'                 => 'Sind Sie sicher, dass Sie alle Zyklen abbrechen wollen?',
    'MODULE_PAYMENT_NOVALNET_REMAINING_CYCLES_ERROR_MESSAGE'          => 'Sind Sie sicher, dass Sie die verbleibenden Zyklen abbrechen wollen?',
    'MODULE_PAYMENT_NOVALNET_INSTALMENT_CANCEL_REMAINING_CYCLES'      => 'Alle übrigen Installationen abbrechen',
    'MODULE_PAYMENT_NOVALNET_INSTALMENT_CANCEL_ALLCYCLES'             => 'Gesamte Ratenzahlung stornieren',
    'MODULE_PAYMENT_NOVALNET_INSTALMENT_SNO_BACKEND'                  => 'S.Nr',
    'MODULE_PAYMENT_NOVALNET_INSTALMENT_REFERENCE_BACKEND'            => 'Novalnet-Transaktions-ID',
    'MODULE_PAYMENT_NOVALNET_INSTALMENT_AMOUNT_BACKEND'               => 'Betrag',
    'MODULE_PAYMENT_NOVALNET_INSTALMENT_DATE_BACKEND'                 => 'Nächster Ratenzahlung Datum',
    'MODULE_PAYMENT_NOVALNET_INSTALMENT_STATUS_BACKEND'               => 'Status',
    'MODULE_PAYMENT_NOVALNET_INSTALMENT_REFUND_EXTENSION_BACKEND'     => 'Verlängerung der Erstattung',
    'MODULE_PAYMENT_NOVALNET_INSTALMENT_STATUS_PAID'                  => 'Bezahlt',
    'MODULE_PAYMENT_NOVALNET_INSTALMENT_STATUS_PENDING'               => 'Ausstehend',
    'MODULE_PAYMENT_NOVALNET_INSTALMENT_STATUS_REFUNDED'              => 'Rückerstattet',
    'MODULE_PAYMENT_NOVALNET_INSTALMENT_STATUS_CANCELED'              => 'Abgesagt',
    'MODULE_PAYMENT_NOVALNET_REFUND_TEXT'                             => 'Rückerstattung',
    'MODULE_PAYMENT_NOVALNET_INSTALMENT_CANCEL_TEXT'                  => 'Stornieren',
    'MODULE_PAYMENT_NOVALNET_INSTALMENT_CANCEL_REMAINING_CYCLES_TEXT' => 'Die Ratenzahlung für die TID wurde gestoppt: %1$s um %2$s',
    'MODULE_PAYMENT_NOVALNET_INSTALMENT_CANCEL_ALLCYCLES_TEXT'        => 'Die Ratenzahlung für die TID wurde gekündigt: %1$s am %2$s',
    'MODULE_PAYMENT_NOVALNET_REFUND_AMT_EXCEED_ERROR'                 => 'Der eingegebene Betrag (%1$s) überschreitet den zulässigen Höchstwert (%2$s)',
    'MODULE_PAYMENT_NOVALNET_BOOK_TITLE'                              => 'Transaktion durchf&uuml;hren',
    'MODULE_PAYMENT_NOVALNET_BOOK_AMT_TITLE'                          => 'Buchungsbetrag der Transaktion',
    'MODULE_PAYMENT_NOVALNET_TRANS_BOOKED_MESSAGE'                    => 'Ihre Bestellung wurde mit einem Betrag von %s gebucht. Ihre neue TID für den gebuchten Betrag: %s',
    'MODULE_PAYMENT_NOVALNET_TRANS_CONFIRM_TITLE'                     => '<b>Transaktion verwalten</b>',
    'MODULE_PAYMENT_NOVALNET_PAYMENT_ZERO_AMOUNT_BOOK_CONFIRM'        => 'Sind Sie sich sicher, dass Sie den Bestellbetrag buchen wollen?',
    'MODULE_PAYMENT_NOVALNET_PAYMENT_CAPTURE_CONFIRM'                 => 'Sind Sie sicher, dass Sie die Zahlung erfassen wollen?',
    'MODULE_PAYMENT_NOVALNET_PAYMENT_VOID_CONFIRM'                    => 'Sind Sie sicher, dass Sie die Zahlung stornieren möchten?',
    'MODULE_PAYMENT_NOVALNET_SELECT_STATUS_TEXT'                      => 'Bitte Status auswählen',
    'MODULE_PAYMENT_NOVALNET_SELECT_STATUS_OPTION'                    => '--Auswählen--',
    'MODULE_PAYMENT_NOVALNET_CANCEL_TEXT'                             => 'Stornieren',
    'MODULE_PAYMENT_NOVALNET_TRANS_DEACTIVATED_MESSAGE'               => 'Die Transaktion wurde am %1$s um %2$s Uhr storniert',
    'MODULE_PAYMENT_NOVALNET_TRANS_CONFIRM_SUCCESSFUL_MESSAGE'        => 'Die Buchung wurde am %1$s um %2$s Uhr bestätigt',
];
