<?php
/* --------------------------------------------------------------
   novalnet_payment.lang.inc.php
   --------------------------------------------------------------
*/

$t_language_text_section_content_array = [
    'MODULE_PAYMENT_NOVALNET_REFUND_TITLE'                            => 'Refund process',
    'MODULE_PAYMENT_NOVALNET_TRANSACTION_ID'                          => 'Novalnet transaction ID: ',
    'MODULE_PAYMENT_NOVALNET_PAYMENT_REFUND_CONFIRM'                  => 'Are you sure you want to refund the amount',
    'MODULE_PAYMENT_NOVALNET_REFUND_AMT_TITLE'                        => 'Please enter the refund amount',
    'MODULE_PAYMENT_NOVALNET_AMOUNT_EX'                               => '   (in minimum unit of currency. E.g. enter 100 which is equal to 1.00)',
    'MODULE_PAYMENT_NOVALNET_REFUND_REASON_TITLE'                     => 'Refund / Cancellation Reason',
    'MODULE_PAYMENT_NOVALNET_CONFIRM_TEXT'                            => 'Confirm',
    'MODULE_PAYMENT_NOVALNET_BACK_TEXT'                               => 'Back',
    'MODULE_PAYMENT_NOVALNET_AMOUNT_ERROR_MESSAGE'                    => 'The amount is invalid',
    'ERROR_ORDER_ACTION_NOT_FOUND'                                    => 'The requested action process was not found',
    'MODULE_PAYMENT_NOVALNET_REFUND_PARENT_TID_MSG'                   => 'Refund has been initiated for the TID: %1$s with the amount of %2$s.',
    'MODULE_PAYMENT_NOVALNET_REFUND_CHILD_TID_MSG'                    => 'New TID:%s for the refunded amount',
    'MODULE_PAYMENT_NOVALNET_INSTALMENT_SUMMARY_BACKEND'              => 'Instalment summary',
    'MODULE_PAYMENT_NOVALNET_INSTALMENT_CANCEL_ADMIN_TEXT'            => 'Instalment cancel',
    'MODULE_PAYMENT_NOVALNET_ALLCYCLES_ERROR_MESSAGE'                 => 'Are you sure you want to cancel all cycles?',
    'MODULE_PAYMENT_NOVALNET_REMAINING_CYCLES_ERROR_MESSAGE'          => 'Are you sure you want to cancel remaining cycles?',
    'MODULE_PAYMENT_NOVALNET_INSTALMENT_CANCEL_REMAINING_CYCLES'      => 'Cancel All Remaining Instalments',
    'MODULE_PAYMENT_NOVALNET_INSTALMENT_CANCEL_ALLCYCLES'             => 'Cancel All Instalments',
    'MODULE_PAYMENT_NOVALNET_INSTALMENT_SNO_BACKEND'                  => 'S.No',
    'MODULE_PAYMENT_NOVALNET_INSTALMENT_REFERENCE_BACKEND'            => 'Novalnet Transaction ID',
    'MODULE_PAYMENT_NOVALNET_INSTALMENT_AMOUNT_BACKEND'               => 'Amount',
    'MODULE_PAYMENT_NOVALNET_INSTALMENT_DATE_BACKEND'                 => 'Next Instalment Date',
    'MODULE_PAYMENT_NOVALNET_INSTALMENT_STATUS_BACKEND'               => 'Status',
    'MODULE_PAYMENT_NOVALNET_INSTALMENT_REFUND_EXTENSION_BACKEND'     => 'Refund Extension',
    'MODULE_PAYMENT_NOVALNET_INSTALMENT_STATUS_PAID'                  => 'Paid',
    'MODULE_PAYMENT_NOVALNET_INSTALMENT_STATUS_PENDING'               => 'Pending',
    'MODULE_PAYMENT_NOVALNET_INSTALMENT_STATUS_REFUNDED'              => 'Refunded',
    'MODULE_PAYMENT_NOVALNET_INSTALMENT_STATUS_CANCELED'              => 'Canceled',
    'MODULE_PAYMENT_NOVALNET_REFUND_TEXT'                             => 'Refund',
    'MODULE_PAYMENT_NOVALNET_INSTALMENT_CANCEL_TEXT'                  => 'Cancel',
    'MODULE_PAYMENT_NOVALNET_INSTALMENT_CANCEL_REMAINING_CYCLES_TEXT' => 'Instalment has been stopped for the TID: %1$s on %2$s',
    'MODULE_PAYMENT_NOVALNET_INSTALMENT_CANCEL_ALLCYCLES_TEXT'        => 'Instalment has been cancelled for the TID: %1$s on %2$s',
    'MODULE_PAYMENT_NOVALNET_REFUND_AMT_EXCEED_ERROR'                 => 'Entered amount(%1$s) exceeds the maximum allowed value(%2$s)',
    'MODULE_PAYMENT_NOVALNET_BOOK_TITLE'                              => 'Book transaction',
    'MODULE_PAYMENT_NOVALNET_BOOK_AMT_TITLE'                          => 'Transaction booking amount',
    'MODULE_PAYMENT_NOVALNET_TRANS_BOOKED_MESSAGE'                    => 'Your order has been booked with the amount of %s. Your new TID for the booked amount: %s',
    'MODULE_PAYMENT_NOVALNET_TRANS_CONFIRM_TITLE'                     => '<b>Manage Transaction</b>',
    'MODULE_PAYMENT_NOVALNET_PAYMENT_ZERO_AMOUNT_BOOK_CONFIRM'        => 'Are you sure you want to book the order amount?',
    'MODULE_PAYMENT_NOVALNET_PAYMENT_CAPTURE_CONFIRM'                 => 'Are you sure you want to capture the payment?',
    'MODULE_PAYMENT_NOVALNET_PAYMENT_VOID_CONFIRM'                    => 'Are you sure you want to cancel the payment?',
    'MODULE_PAYMENT_NOVALNET_SELECT_STATUS_TEXT'                      => 'Please select status',
    'MODULE_PAYMENT_NOVALNET_SELECT_STATUS_OPTION'                    => '--Select--',
    'MODULE_PAYMENT_NOVALNET_CANCEL_TEXT'                             => 'Cancel',
    'MODULE_PAYMENT_NOVALNET_TRANS_DEACTIVATED_MESSAGE'               => 'The transaction has been canceled on %1$s, %2$s',
    'MODULE_PAYMENT_NOVALNET_TRANS_CONFIRM_SUCCESSFUL_MESSAGE'        => 'The transaction has been confirmed on %1$s, %2$s',
];
